# Generated by Django 5.2.3 on 2025-07-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]