# Generated by Django 5.2.3 on 2025-07-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_usercredential_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
